pages:
  tags:
    - ruby:2.3.3
  stage: deploy
  script:
    - bundle install
    - export LANG=en_US.UTF-8
    - echo $LANG
    - nanoc compile 
    - cp -a output/* public/
  artifacts:
    paths:
      - public
  only:
    - master    