pages:
  tags:
    - ruby:2.3.3
  stage: deploy
  script:
    - cp Gemfile.gitlab-ci Gemfile
    - bundle install  -j4
    - export LANG=en_US.UTF-8
    - export LC_CTYPE=en_US.UTF-8
    - echo $LANG $LC_CTYPE
    - nanoc compile
    - cp -a output/* public/
  artifacts:
    paths:
      - public
  only:
    - master