pages:
  tags:
    - ruby-2-7
  stage: deploy
  script:
    - sudo apt-get install libcurl4 libcurl3-gnutls libcurl4-openssl-dev  
    - cp Gemfile.gitlab-ci Gemfile
    - bundle install  -j4
    - export LC_ALL=C.UTF-8
    - export LANG=C
    - export LANGUAGE=C.UTF-8
    - echo $LC_ALL $LANG $LANGUAGE 
    - locale
    - nanoc compile
    - mkdir -p public
    - cp -a output/* public/
  artifacts:
    paths:
      - public
  only:
    - master
