name: Build Static Site with Nanoc
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install libcurl
      run: sudo apt-get install libcurl4 libcurl3-gnutls libcurl4-openssl-dev
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.1 # Not needed with a .ruby-version file
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - run: bundle exec nanoc compile
